import{i as f,a as L,S as y}from"./assets/vendor-Qob_5Ba8.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const d of r.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&s(d)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const v="46197993-0238acfcd6230053ff5f60fb7",w="https://pixabay.com/api/",S=document.querySelector("#search-form"),m=document.querySelector(".search-input"),h=document.querySelector("#gallery"),i=document.querySelector("#load-more"),u=document.querySelector("#loading-message");let c="",n=1,p=0,l=!1;async function g(a,t=1){if(!l){l=!0,u.style.display="block";try{const o=await L.get(`${w}`,{params:{key:v,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:40,page:t}});return p=o.data.totalHits,u.style.display="none",l=!1,o.data}catch(o){u.style.display="none",l=!1,console.error("Hata oluştu:",o)}}}function b(a){const t=a.map(s=>`
        <li class="gallery-item">
          <a href="${s.largeImageURL}">
            <img src="${s.webformatURL}" alt="${s.tags}" loading="lazy" />
          </a>
          <div class="info">
            <p><b>Likes:</b> ${s.likes}</p>
            <p><b>Views:</b> ${s.views}</p>
            <p><b>Comments:</b> ${s.comments}</p>
            <p><b>Downloads:</b> ${s.downloads}</p>
          </div>
        </li>
      `).join("");h.insertAdjacentHTML("beforeend",t);const o=new y(".gallery a",{captionsData:"alt",captionDelay:250});o?o.refresh():o=new y(".gallery a")}S.addEventListener("submit",async a=>{if(a.preventDefault(),h.innerHTML="",c=m.value.trim(),!c)return;n=1;const t=await g(c,n);if(t.hits.length===0){i.style.display="none",f.error({title:"No Results",message:"No images found. Please try a different query.",position:"topRight"});return}b(t.hits),i.style.display="block",m.value="",n*40>=p&&(i.style.display="none",f.error({title:"Sorry",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))});i.addEventListener("click",async()=>{n+=1;const a=await g(c,n);b(a.hits),n*40>=p&&(i.style.display="none",f.error({title:"Sorry",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}));const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})});
//# sourceMappingURL=index.js.map
